version: '3'
services:
  app:
    build:
      context: "."
    ports:
      # TODO: solr-port
      - "${WEBPORT:-80}:80"
    volumes:
      - "${CONFIG:-./config}:/var/www/html/config"
      - "${BASE_OUTPUT_DIR:-./metadata-qa}:/var/www/html/metadata-qa"
